### ISSUE TITLE
Добавить файл Info.md

### ISSUE THREAD

**Issue by Aleksey-Denisov** [Aleksey-Denisov/GBGIT#1]
Сначала надо будет в задаче написать коммент что-то вроде в работе
1 Сделать клон проекта
2 Создать ветку назвать ее примерно номер задачи_addInfo
3 Сделать изменения создать файл и наверное даже текст задачи прокатит:
Данное домашнее задание является продолжением домашнего задания, которое вы выполняли на предыдущем семинаре в репозитории с собственным проектом.

В этом задании предлагаем каждому из вас побыть в роли тимлида.

1. Пригласите в свой проект кого-то из коллег по обучению, дайте им доступ к своему репозиторию (кроме ветки master).

2. Поставьте ему в GitHub задачу по своему проекту, попросите её выполнить в отдельной ветке, а после выполнения — создать pull request и перевести задачу обратно на вас.

3. Проверьте выполнение задачи, примите pull request и удалите ветку, в которой решалась данная задача

Или что угодно добавить туда

4 Сделать коммит и пуш в гитхаб
5 Создать пул реквест при его создании в адресной строке скопировать ссылку этого пулреквеста
6 Вернуться к задаче и вставить ссылку через пробел дописать все готово и нажать кнопку коммент

**Comment by MavrinSergey** [comment]
Взял в работу

**Comment by MavrinSergey** [comment]
https://github.com/Aleksey-Denisov/GBGIT/pull/2 сделал

**Comment by Aleksey-Denisov** [comment]
В проде
